// IPO Dashboard Data — US-listed IPOs 2020-2025
// Source: Excel master dataset + yfinance market caps, May 2026
// 94 companies across all valuation tiers

export const COMPANIES = [
    {
      year: 2021,
      ticker: "HOOD",
      company: "Robinhood Markets",
      sector: "Fintech",
      subSector: "Fintech / brokerage",
      ipoVal: 8,
      currentCap: 70.485,
      ret: 7.8106,
      moic: 8.8106,
      bucket: "$7-10B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 367,
      spyAtIPO: 441,
      qqqRet: 0.9635,
      spyRet: 0.3764,
      alphaQQQ: 6.847,
      alphaSPY: 7.434,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "BMBL",
      company: "Bumble",
      sector: "Consumer",
      subSector: "Consumer internet / dating",
      ipoVal: 8.2,
      currentCap: 0.472,
      ret: -0.9424,
      moic: 0.0576,
      bucket: "$7-10B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 338,
      spyAtIPO: 392,
      qqqRet: 1.1319,
      spyRet: 0.5485,
      alphaQQQ: -2.074,
      alphaSPY: -1.491,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "DUOL",
      company: "Duolingo",
      sector: "Consumer",
      subSector: "Edtech / consumer software",
      ipoVal: 3.7,
      currentCap: 5.032,
      ret: 0.36,
      moic: 1.36,
      bucket: "$3-5B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 367,
      spyAtIPO: 440,
      qqqRet: 0.9635,
      spyRet: 0.3795,
      alphaQQQ: -0.603,
      alphaSPY: -0.02,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "WRBY",
      company: "Warby Parker",
      sector: "Consumer",
      subSector: "Consumer retail / DTC",
      ipoVal: 6,
      currentCap: 3.71,
      ret: -0.3817,
      moic: 0.6183,
      bucket: "$5-7B",
      outcome: "Moderate Loss",
      listingType: "Direct listing",
      status: "Active",
      qqqAtIPO: 363,
      spyAtIPO: 432,
      qqqRet: 0.9851,
      spyRet: 0.4051,
      alphaQQQ: -1.367,
      alphaSPY: -0.787,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "BIRD",
      company: "Allbirds",
      sector: "Consumer",
      subSector: "Consumer retail / DTC",
      ipoVal: 4.1,
      currentCap: 0.046,
      ret: -0.9888,
      moic: 0.0112,
      bucket: "$3-5B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 397,
      spyAtIPO: 464,
      qqqRet: 0.8151,
      spyRet: 0.3082,
      alphaQQQ: -1.804,
      alphaSPY: -1.297,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "SG",
      company: "Sweetgreen",
      sector: "Consumer",
      subSector: "Restaurants / consumer",
      ipoVal: 5.5,
      currentCap: 0.842,
      ret: -0.8469,
      moic: 0.1531,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 399,
      spyAtIPO: 468,
      qqqRet: 0.806,
      spyRet: 0.297,
      alphaQQQ: -1.653,
      alphaSPY: -1.144,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "BRZE",
      company: "Braze",
      sector: "SaaS / Software",
      subSector: "SaaS / customer engagement",
      ipoVal: 6,
      currentCap: 2.338,
      ret: -0.6103,
      moic: 0.3897,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 402,
      spyAtIPO: 470,
      qqqRet: 0.7925,
      spyRet: 0.2915,
      alphaQQQ: -1.403,
      alphaSPY: -0.902,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "UDMY",
      company: "Udemy",
      sector: "Marketplace / Commerce",
      subSector: "Edtech marketplace",
      ipoVal: 3.7,
      currentCap: 0.704,
      ret: -0.8097,
      moic: 0.1903,
      bucket: "$3-5B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 387,
      spyAtIPO: 461,
      qqqRet: 0.862,
      spyRet: 0.3167,
      alphaQQQ: -1.672,
      alphaSPY: -1.126,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "NRDS",
      company: "NerdWallet",
      sector: "Fintech",
      subSector: "Fintech / consumer finance",
      ipoVal: 1.2,
      currentCap: 0.635,
      ret: -0.4708,
      moic: 0.5292,
      bucket: "$1-2B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 399,
      spyAtIPO: 466,
      qqqRet: 0.806,
      spyRet: 0.3026,
      alphaQQQ: -1.277,
      alphaSPY: -0.773,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "COUR",
      company: "Coursera",
      sector: "Edtech",
      subSector: "Edtech / online learning",
      ipoVal: 4.3,
      currentCap: 0.975,
      ret: -0.7733,
      moic: 0.2267,
      bucket: "$3-5B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 330,
      spyAtIPO: 396,
      qqqRet: 1.1836,
      spyRet: 0.5328,
      alphaQQQ: -1.957,
      alphaSPY: -1.306,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "COMP",
      company: "Compass",
      sector: "Real Estate / Proptech",
      subSector: "Real estate tech",
      ipoVal: 8,
      currentCap: 7.18,
      ret: -0.1025,
      moic: 0.8975,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 334,
      spyAtIPO: 400,
      qqqRet: 1.1575,
      spyRet: 0.5175,
      alphaQQQ: -1.26,
      alphaSPY: -0.62,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "GLBE",
      company: "Global-e Online",
      sector: "Marketplace / Commerce",
      subSector: "Ecommerce infrastructure",
      ipoVal: 3.6,
      currentCap: 4.976,
      ret: 0.3822,
      moic: 1.3822,
      bucket: "$3-5B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 325,
      spyAtIPO: 413,
      qqqRet: 1.2172,
      spyRet: 0.4697,
      alphaQQQ: -0.835,
      alphaSPY: -0.088,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "LZ",
      company: "LegalZoom",
      sector: "Legaltech",
      subSector: "Legaltech / SMB services",
      ipoVal: 7,
      currentCap: 1.085,
      ret: -0.845,
      moic: 0.155,
      bucket: "$7-10B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 356,
      spyAtIPO: 429,
      qqqRet: 1.0241,
      spyRet: 0.4149,
      alphaQQQ: -1.869,
      alphaSPY: -1.26,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "MQ",
      company: "Marqeta",
      sector: "Fintech",
      subSector: "Payments infrastructure",
      ipoVal: 8.6,
      currentCap: 1.808,
      ret: -0.7898,
      moic: 0.2102,
      bucket: "$7-10B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 341,
      spyAtIPO: 422,
      qqqRet: 1.1132,
      spyRet: 0.4384,
      alphaQQQ: -1.903,
      alphaSPY: -1.228,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "MNDY",
      company: "Monday.com",
      sector: "SaaS / Software",
      subSector: "SaaS / work management",
      ipoVal: 6.8,
      currentCap: 3.526,
      ret: -0.4815,
      moic: 0.5185,
      bucket: "$5-7B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 342,
      spyAtIPO: 423,
      qqqRet: 1.107,
      spyRet: 0.435,
      alphaQQQ: -1.588,
      alphaSPY: -0.916,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "RYAN",
      company: "Ryan Specialty",
      sector: "Insurance",
      subSector: "Insurance distribution",
      ipoVal: 6,
      currentCap: 4.3,
      ret: -0.2833,
      moic: 0.7167,
      bucket: "$5-7B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 364,
      spyAtIPO: 439,
      qqqRet: 0.9796,
      spyRet: 0.3827,
      alphaQQQ: -1.263,
      alphaSPY: -0.666,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2022,
      ticker: "TPG",
      company: "TPG Inc.",
      sector: "Asset Management",
      subSector: "Asset management",
      ipoVal: 9.1,
      currentCap: 17.121,
      ret: 0.8814,
      moic: 1.8814,
      bucket: "$7-10B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 385,
      spyAtIPO: 464,
      qqqRet: 0.8717,
      spyRet: 0.3082,
      alphaQQQ: 0.01,
      alphaSPY: 0.573,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2022,
      ticker: "BLCO",
      company: "Bausch + Lomb",
      sector: "Healthcare",
      subSector: "Healthcare / eye care",
      ipoVal: 6.3,
      currentCap: 5.747,
      ret: -0.0878,
      moic: 0.9122,
      bucket: "$5-7B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 308,
      spyAtIPO: 411,
      qqqRet: 1.3396,
      spyRet: 0.4769,
      alphaQQQ: -1.427,
      alphaSPY: -0.565,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2022,
      ticker: "CRDO",
      company: "Credo Technology",
      sector: "Semiconductors",
      subSector: "Semiconductor connectivity",
      ipoVal: 1.6,
      currentCap: 36.197,
      ret: 21.6231,
      moic: 22.6231,
      bucket: "$1-2B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 354,
      spyAtIPO: 434,
      qqqRet: 1.0356,
      spyRet: 0.3986,
      alphaQQQ: 20.588,
      alphaSPY: 21.225,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2022,
      ticker: "ATAT",
      company: "Atour Lifestyle",
      sector: "Hospitality",
      subSector: "Hospitality / China ADR",
      ipoVal: 1.5,
      currentCap: 15.723,
      ret: 9.482,
      moic: 10.482,
      bucket: "$1-2B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 283,
      spyAtIPO: 395,
      qqqRet: 1.5463,
      spyRet: 0.5367,
      alphaQQQ: 7.936,
      alphaSPY: 8.945,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2022,
      ticker: "TXO",
      company: "TXO Partners",
      sector: "Energy / Industrials",
      subSector: "Energy / E&P LP",
      ipoVal: 0.7,
      currentCap: 0.678,
      ret: -0.0314,
      moic: 0.9686,
      bucket: "<$1B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 278,
      spyAtIPO: 374,
      qqqRet: 1.5921,
      spyRet: 0.623,
      alphaQQQ: -1.623,
      alphaSPY: -0.654,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "CAVA",
      company: "Cava Group",
      sector: "Consumer",
      subSector: "Restaurants / consumer",
      ipoVal: 2.5,
      currentCap: 9.391,
      ret: 2.7564,
      moic: 3.7564,
      bucket: "$2-3B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 370,
      spyAtIPO: 443,
      qqqRet: 0.9475,
      spyRet: 0.3702,
      alphaQQQ: 1.809,
      alphaSPY: 2.386,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "CART",
      company: "Instacart / Maplebear",
      sector: "Marketplace / Commerce",
      subSector: "Grocery marketplace",
      ipoVal: 9.9,
      currentCap: 10.233,
      ret: 0.0336,
      moic: 1.0336,
      bucket: "$7-10B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 370,
      spyAtIPO: 444,
      qqqRet: 0.9475,
      spyRet: 0.3671,
      alphaQQQ: -0.914,
      alphaSPY: -0.333,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "KVYO",
      company: "Klaviyo",
      sector: "SaaS / Software",
      subSector: "SaaS / marketing automation",
      ipoVal: 9.2,
      currentCap: 4.651,
      ret: -0.4945,
      moic: 0.5055,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 367,
      spyAtIPO: 435,
      qqqRet: 0.9635,
      spyRet: 0.3954,
      alphaQQQ: -1.458,
      alphaSPY: -0.89,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "BIRK",
      company: "Birkenstock",
      sector: "Consumer",
      subSector: "Consumer / footwear",
      ipoVal: 8.6,
      currentCap: 7.389,
      ret: -0.1408,
      moic: 0.8592,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 374,
      spyAtIPO: 438,
      qqqRet: 0.9267,
      spyRet: 0.3858,
      alphaQQQ: -1.068,
      alphaSPY: -0.527,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "NXT",
      company: "Nextracker",
      sector: "Energy / Industrials",
      subSector: "Solar / energy infrastructure",
      ipoVal: 3.5,
      currentCap: 19.38,
      ret: 4.5371,
      moic: 5.5371,
      bucket: "$3-5B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 299,
      spyAtIPO: 411,
      qqqRet: 1.41,
      spyRet: 0.4769,
      alphaQQQ: 3.127,
      alphaSPY: 4.06,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "ODD",
      company: "Oddity Tech",
      sector: "Consumer",
      subSector: "Beauty / consumer tech",
      ipoVal: 2.8,
      currentCap: 0.841,
      ret: -0.6996,
      moic: 0.3004,
      bucket: "$2-3B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 385,
      spyAtIPO: 455,
      qqqRet: 0.8717,
      spyRet: 0.3341,
      alphaQQQ: -1.571,
      alphaSPY: -1.034,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "KGS",
      company: "Kodiak Gas Services",
      sector: "Energy / Industrials",
      subSector: "Energy infrastructure",
      ipoVal: 1.2,
      currentCap: 6.063,
      ret: 4.0525,
      moic: 5.0525,
      bucket: "$1-2B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 372,
      spyAtIPO: 443,
      qqqRet: 0.9371,
      spyRet: 0.3702,
      alphaQQQ: 3.115,
      alphaSPY: 3.682,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "APGE",
      company: "Apogee Therapeutics",
      sector: "Healthcare",
      subSector: "Biotech",
      ipoVal: 0.9,
      currentCap: 4.88,
      ret: 4.4222,
      moic: 5.4222,
      bucket: "<$1B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 381,
      spyAtIPO: 452,
      qqqRet: 0.8913,
      spyRet: 0.3429,
      alphaQQQ: 3.531,
      alphaSPY: 4.079,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "CRGX",
      company: "CARGO Therapeutics",
      sector: "Healthcare",
      subSector: "Biotech",
      ipoVal: 0.9,
      currentCap: 0.19,
      ret: -0.7889,
      moic: 0.2111,
      bucket: "<$1B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 374,
      spyAtIPO: 450,
      qqqRet: 0.9267,
      spyRet: 0.3489,
      alphaQQQ: -1.716,
      alphaSPY: -1.138,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "LXEO",
      company: "Lexeo Therapeutics",
      sector: "Healthcare",
      subSector: "Biotech",
      ipoVal: 0.5,
      currentCap: 0.356,
      ret: -0.288,
      moic: 0.712,
      bucket: "<$1B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 387,
      spyAtIPO: 452,
      qqqRet: 0.862,
      spyRet: 0.3429,
      alphaQQQ: -1.15,
      alphaSPY: -0.631,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "GPCR",
      company: "Structure Therapeutics",
      sector: "Healthcare",
      subSector: "Biotech / metabolic",
      ipoVal: 0.8,
      currentCap: 8.497,
      ret: 9.6212,
      moic: 10.6212,
      bucket: "<$1B",
      outcome: "100%+ Winner",
      listingType: "ADR IPO",
      status: "Active",
      qqqAtIPO: 304,
      spyAtIPO: 415,
      qqqRet: 1.3704,
      spyRet: 0.4627,
      alphaQQQ: 8.251,
      alphaSPY: 9.159,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2023,
      ticker: "HSAI",
      company: "Hesai Group",
      sector: "Mobility / Transport",
      subSector: "LiDAR / autonomy",
      ipoVal: 2.4,
      currentCap: 2.801,
      ret: 0.1671,
      moic: 1.1671,
      bucket: "$2-3B",
      outcome: "Positive",
      listingType: "ADR IPO",
      status: "Active",
      qqqAtIPO: 299,
      spyAtIPO: 411,
      qqqRet: 1.41,
      spyRet: 0.4769,
      alphaQQQ: -1.243,
      alphaSPY: -0.31,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "RDDT",
      company: "Reddit",
      sector: "Consumer",
      subSector: "Consumer internet / social",
      ipoVal: 6.4,
      currentCap: 31.553,
      ret: 3.9302,
      moic: 4.9302,
      bucket: "$5-7B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 444,
      spyAtIPO: 524,
      qqqRet: 0.623,
      spyRet: 0.1584,
      alphaQQQ: 3.307,
      alphaSPY: 3.772,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "ALAB",
      company: "Astera Labs",
      sector: "Semiconductors",
      subSector: "AI/datacenter semiconductor",
      ipoVal: 5.5,
      currentCap: 36.193,
      ret: 5.5805,
      moic: 6.5805,
      bucket: "$5-7B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 443,
      spyAtIPO: 524,
      qqqRet: 0.6266,
      spyRet: 0.1584,
      alphaQQQ: 4.954,
      alphaSPY: 5.422,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "RBRK",
      company: "Rubrik",
      sector: "Cybersecurity",
      subSector: "Cybersecurity / data security",
      ipoVal: 5.6,
      currentCap: 12.367,
      ret: 1.2084,
      moic: 2.2084,
      bucket: "$5-7B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 430,
      spyAtIPO: 504,
      qqqRet: 0.6758,
      spyRet: 0.2044,
      alphaQQQ: 0.533,
      alphaSPY: 1.004,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "IBTA",
      company: "Ibotta",
      sector: "Consumer",
      subSector: "Adtech / consumer rewards",
      ipoVal: 2.7,
      currentCap: 0.857,
      ret: -0.6826,
      moic: 0.3174,
      bucket: "$2-3B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 432,
      spyAtIPO: 502,
      qqqRet: 0.668,
      spyRet: 0.2092,
      alphaQQQ: -1.351,
      alphaSPY: -0.892,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "WAY",
      company: "Waystar",
      sector: "Fintech",
      subSector: "Healthcare payments software",
      ipoVal: 3.7,
      currentCap: 4.172,
      ret: 0.1276,
      moic: 1.1276,
      bucket: "$3-5B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 465,
      spyAtIPO: 533,
      qqqRet: 0.5497,
      spyRet: 0.1388,
      alphaQQQ: -0.422,
      alphaSPY: -0.011,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "TEM",
      company: "Tempus AI",
      sector: "Healthcare",
      subSector: "Healthcare AI / diagnostics",
      ipoVal: 6.1,
      currentCap: 8.923,
      ret: 0.4628,
      moic: 1.4628,
      bucket: "$5-7B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 478,
      spyAtIPO: 545,
      qqqRet: 0.5075,
      spyRet: 0.1138,
      alphaQQQ: -0.045,
      alphaSPY: 0.349,
      beatQQQ: false,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "LINE",
      company: "Lineage",
      sector: "Energy / Industrials",
      subSector: "Cold-storage REIT",
      ipoVal: 9.2,
      currentCap: 9.071,
      ret: -0.014,
      moic: 0.986,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 472,
      spyAtIPO: 542,
      qqqRet: 0.5267,
      spyRet: 0.1199,
      alphaQQQ: -0.541,
      alphaSPY: -0.134,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "TWG",
      company: "Top Wealth Group",
      sector: "Consumer",
      subSector: "Consumer / microcap",
      ipoVal: 0.1,
      currentCap: 0.097,
      ret: -0.03,
      moic: 0.97,
      bucket: "<$1B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 475,
      spyAtIPO: 562,
      qqqRet: 0.517,
      spyRet: 0.0801,
      alphaQQQ: -0.547,
      alphaSPY: -0.11,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2024,
      ticker: "SRVT",
      company: "ServiceTitan",
      sector: "SaaS / Software",
      subSector: "SaaS / field service mgmt",
      ipoVal: 7.4,
      currentCap: 8.5,
      ret: 0.1486,
      moic: 1.1486,
      bucket: "$7-10B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 535,
      spyAtIPO: 607,
      qqqRet: 0.3469,
      spyRet: 0.0,
      alphaQQQ: -0.198,
      alphaSPY: 0.149,
      beatQQQ: false,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "GEMI",
      company: "Gemini Space Station",
      sector: "Crypto / Web3",
      subSector: "Crypto exchange",
      ipoVal: 3.3,
      currentCap: 0.35,
      ret: -0.8939,
      moic: 0.1061,
      bucket: "$3-5B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 450,
      spyAtIPO: 537,
      qqqRet: 0.6013,
      spyRet: 0.1304,
      alphaQQQ: -1.495,
      alphaSPY: -1.024,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "FIGR",
      company: "Figure Technology",
      sector: "Fintech",
      subSector: "Fintech / blockchain",
      ipoVal: 5.3,
      currentCap: 2.1,
      ret: -0.6038,
      moic: 0.3962,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 430,
      spyAtIPO: 505,
      qqqRet: 0.6758,
      spyRet: 0.202,
      alphaQQQ: -1.28,
      alphaSPY: -0.806,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "STUB",
      company: "StubHub",
      sector: "Marketplace / Commerce",
      subSector: "Marketplace / ticketing",
      ipoVal: 8.6,
      currentCap: 1,
      ret: -0.8837,
      moic: 0.1163,
      bucket: "$7-10B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 482,
      spyAtIPO: 558,
      qqqRet: 0.495,
      spyRet: 0.0878,
      alphaQQQ: -1.379,
      alphaSPY: -0.972,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "VIA",
      company: "Via Transportation",
      sector: "Mobility / Transport",
      subSector: "Mobility software",
      ipoVal: 3.5,
      currentCap: 1.4,
      ret: -0.6,
      moic: 0.4,
      bucket: "$3-5B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 470,
      spyAtIPO: 556,
      qqqRet: 0.5332,
      spyRet: 0.0917,
      alphaQQQ: -1.133,
      alphaSPY: -0.692,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "MDLN",
      company: "Medline",
      sector: "Healthcare",
      subSector: "Medical supplies",
      ipoVal: 38,
      currentCap: 36.3,
      ret: -0.0447,
      moic: 0.9553,
      bucket: "$20-40B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 532,
      spyAtIPO: 605,
      qqqRet: 0.3545,
      spyRet: 0.0033,
      alphaQQQ: -0.399,
      alphaSPY: -0.048,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$20-40B"
    },
    {
      year: 2025,
      ticker: "ETOR",
      company: "eToro Group",
      sector: "Fintech",
      subSector: "Fintech / trading",
      ipoVal: 4.2,
      currentCap: 3.14,
      ret: -0.2524,
      moic: 0.7476,
      bucket: "$3-5B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 500,
      spyAtIPO: 568,
      qqqRet: 0.4412,
      spyRet: 0.0687,
      alphaQQQ: -0.694,
      alphaSPY: -0.321,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "CHYM",
      company: "Chime Financial",
      sector: "Fintech",
      subSector: "Fintech / neobank",
      ipoVal: 8.6,
      currentCap: 8.3,
      ret: -0.0349,
      moic: 0.9651,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 530,
      spyAtIPO: 594,
      qqqRet: 0.3596,
      spyRet: 0.0219,
      alphaQQQ: -0.394,
      alphaSPY: -0.057,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "CRCL",
      company: "Circle Internet",
      sector: "Crypto / Web3",
      subSector: "Crypto / stablecoin",
      ipoVal: 5.4,
      currentCap: 28.2,
      ret: 4.2222,
      moic: 5.2222,
      bucket: "$5-7B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 485,
      spyAtIPO: 556,
      qqqRet: 0.4858,
      spyRet: 0.0917,
      alphaQQQ: 3.736,
      alphaSPY: 4.13,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "KLAR",
      company: "Klarna Group",
      sector: "Fintech",
      subSector: "Fintech / BNPL",
      ipoVal: 7.5,
      currentCap: 5.47,
      ret: -0.2707,
      moic: 0.7293,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 492,
      spyAtIPO: 558,
      qqqRet: 0.4646,
      spyRet: 0.0878,
      alphaQQQ: -0.735,
      alphaSPY: -0.358,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "FIG",
      company: "Figma",
      sector: "SaaS / Software",
      subSector: "SaaS / design",
      ipoVal: 8.3,
      currentCap: 10.8,
      ret: 0.3012,
      moic: 1.3012,
      bucket: "$7-10B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 535,
      spyAtIPO: 587,
      qqqRet: 0.3469,
      spyRet: 0.0341,
      alphaQQQ: -0.046,
      alphaSPY: 0.267,
      beatQQQ: false,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "MNTN",
      company: "MNTN Inc.",
      sector: "Adtech",
      subSector: "Adtech / CTV",
      ipoVal: 1.5,
      currentCap: 1.2,
      ret: -0.2,
      moic: 0.8,
      bucket: "$1-2B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 522,
      spyAtIPO: 588,
      qqqRet: 0.3804,
      spyRet: 0.0323,
      alphaQQQ: -0.58,
      alphaSPY: -0.232,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "HNGE",
      company: "Hinge Health",
      sector: "Healthcare",
      subSector: "Healthtech / digital MSK",
      ipoVal: 2.5,
      currentCap: 2,
      ret: -0.2,
      moic: 0.8,
      bucket: "$2-3B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 495,
      spyAtIPO: 564,
      qqqRet: 0.4557,
      spyRet: 0.0762,
      alphaQQQ: -0.656,
      alphaSPY: -0.276,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "SLDE",
      company: "Slide Insurance",
      sector: "Insurance",
      subSector: "Insurtech / homeowners",
      ipoVal: 1.5,
      currentCap: 1.2,
      ret: -0.2,
      moic: 0.8,
      bucket: "$1-2B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 527,
      spyAtIPO: 591,
      qqqRet: 0.3673,
      spyRet: 0.0271,
      alphaQQQ: -0.567,
      alphaSPY: -0.227,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$0-10B"
    },
    {
      year: 2025,
      ticker: "VOYG",
      company: "Voyager Technologies",
      sector: "Space / Defense",
      subSector: "Space / defense tech",
      ipoVal: 3.8,
      currentCap: 5,
      ret: 0.3158,
      moic: 1.3158,
      bucket: "$3-5B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 528,
      spyAtIPO: 592,
      qqqRet: 0.3648,
      spyRet: 0.0253,
      alphaQQQ: -0.049,
      alphaSPY: 0.29,
      beatQQQ: false,
      beatSPY: true,
      wideBucket: "$0-10B"
    },
    {
      year: 2021,
      ticker: "RIVN",
      company: "Rivian Automotive",
      sector: "Mobility / Transport",
      subSector: "EV manufacturer",
      ipoVal: 77,
      currentCap: 19,
      ret: -0.7532,
      moic: 0.2468,
      bucket: "$40B+",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 396,
      spyAtIPO: 468,
      qqqRet: 0.8197,
      spyRet: 0.297,
      alphaQQQ: -1.573,
      alphaSPY: -1.05,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$40B+"
    },
    {
      year: 2021,
      ticker: "COIN",
      company: "Coinbase Global",
      sector: "Crypto / Web3",
      subSector: "Crypto exchange",
      ipoVal: 65,
      currentCap: 55,
      ret: -0.1538,
      moic: 0.8462,
      bucket: "$40B+",
      outcome: "Moderate Loss",
      listingType: "Direct listing",
      status: "Active",
      qqqAtIPO: 340,
      spyAtIPO: 412,
      qqqRet: 1.1194,
      spyRet: 0.4733,
      alphaQQQ: -1.273,
      alphaSPY: -0.627,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$40B+"
    },
    {
      year: 2021,
      ticker: "CPNG",
      company: "Coupang",
      sector: "Marketplace / Commerce",
      subSector: "Ecommerce / Korea",
      ipoVal: 60,
      currentCap: 42,
      ret: -0.3,
      moic: 0.7,
      bucket: "$40B+",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 323,
      spyAtIPO: 394,
      qqqRet: 1.2309,
      spyRet: 0.5406,
      alphaQQQ: -1.531,
      alphaSPY: -0.841,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$40B+"
    },
    {
      year: 2021,
      ticker: "DIDI",
      company: "DiDi Global",
      sector: "Mobility / Transport",
      subSector: "Rideshare / China",
      ipoVal: 68,
      currentCap: 0.5,
      ret: -0.9926,
      moic: 0.0074,
      bucket: "$40B+",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Delisted",
      qqqAtIPO: 356,
      spyAtIPO: 429,
      qqqRet: 1.0241,
      spyRet: 0.4149,
      alphaQQQ: -2.017,
      alphaSPY: -1.408,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$40B+"
    },
    {
      year: 2021,
      ticker: "RBLX",
      company: "Roblox",
      sector: "Consumer",
      subSector: "Gaming platform",
      ipoVal: 38,
      currentCap: 38,
      ret: 0,
      moic: 1,
      bucket: "$20-40B",
      outcome: "Positive",
      listingType: "Direct listing",
      status: "Active",
      qqqAtIPO: 316,
      spyAtIPO: 390,
      qqqRet: 1.2803,
      spyRet: 0.5564,
      alphaQQQ: -1.28,
      alphaSPY: -0.556,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$20-40B"
    },
    {
      year: 2021,
      ticker: "TOST",
      company: "Toast",
      sector: "SaaS / Software",
      subSector: "Restaurant SaaS",
      ipoVal: 20,
      currentCap: 18,
      ret: -0.1,
      moic: 0.9,
      bucket: "$20-40B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 370,
      spyAtIPO: 440,
      qqqRet: 0.9475,
      spyRet: 0.3795,
      alphaQQQ: -1.048,
      alphaSPY: -0.48,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$20-40B"
    },
    {
      year: 2021,
      ticker: "ONON",
      company: "On Holding",
      sector: "Consumer",
      subSector: "Athletic footwear",
      ipoVal: 10,
      currentCap: 20,
      ret: 1,
      moic: 2,
      bucket: "$10-20B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 381,
      spyAtIPO: 448,
      qqqRet: 0.8913,
      spyRet: 0.3549,
      alphaQQQ: 0.109,
      alphaSPY: 0.645,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$10-20B"
    },
    {
      year: 2021,
      ticker: "DOCS",
      company: "Doximity",
      sector: "Healthcare",
      subSector: "Healthcare IT platform",
      ipoVal: 11,
      currentCap: 6.5,
      ret: -0.4091,
      moic: 0.5909,
      bucket: "$10-20B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 355,
      spyAtIPO: 428,
      qqqRet: 1.0298,
      spyRet: 0.4182,
      alphaQQQ: -1.439,
      alphaSPY: -0.827,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$10-20B"
    },
    {
      year: 2021,
      ticker: "TASK",
      company: "TaskUs",
      sector: "SaaS / Software",
      subSector: "BPO / outsourcing",
      ipoVal: 10,
      currentCap: 1.5,
      ret: -0.85,
      moic: 0.15,
      bucket: "$10-20B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 341,
      spyAtIPO: 422,
      qqqRet: 1.1132,
      spyRet: 0.4384,
      alphaQQQ: -1.963,
      alphaSPY: -1.288,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$10-20B"
    },
    {
      year: 2021,
      ticker: "XPEV",
      company: "XPeng",
      sector: "Mobility / Transport",
      subSector: "EV / China ADR",
      ipoVal: 15,
      currentCap: 14,
      ret: -0.0667,
      moic: 0.9333,
      bucket: "$10-20B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 374,
      spyAtIPO: 449,
      qqqRet: 0.9267,
      spyRet: 0.3519,
      alphaQQQ: -0.993,
      alphaSPY: -0.419,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$10-20B"
    },
    {
      year: 2021,
      ticker: "DNUT",
      company: "Krispy Kreme",
      sector: "Consumer",
      subSector: "Consumer / QSR",
      ipoVal: 12,
      currentCap: 6.2,
      ret: -0.4833,
      moic: 0.5167,
      bucket: "$10-20B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 358,
      spyAtIPO: 432,
      qqqRet: 1.0128,
      spyRet: 0.4051,
      alphaQQQ: -1.496,
      alphaSPY: -0.888,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$10-20B"
    },
    {
      year: 2023,
      ticker: "ARM",
      company: "ARM Holdings",
      sector: "Semiconductors",
      subSector: "Semiconductor IP",
      ipoVal: 54,
      currentCap: 160,
      ret: 1.963,
      moic: 2.963,
      bucket: "$40B+",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 374,
      spyAtIPO: 450,
      qqqRet: 0.9267,
      spyRet: 0.3489,
      alphaQQQ: 1.036,
      alphaSPY: 1.614,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$40B+"
    },
    {
      year: 2025,
      ticker: "CRWV",
      company: "CoreWeave",
      sector: "AI / Data Infra",
      subSector: "AI cloud infra",
      ipoVal: 23,
      currentCap: 63,
      ret: 1.7391,
      moic: 2.7391,
      bucket: "$20-40B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 468,
      spyAtIPO: 553,
      qqqRet: 0.5397,
      spyRet: 0.0976,
      alphaQQQ: 1.199,
      alphaSPY: 1.641,
      beatQQQ: true,
      beatSPY: true,
      wideBucket: "$20-40B"
    },
    {
      year: 2024,
      ticker: "VG",
      company: "Venture Global",
      sector: "Energy / Industrials",
      subSector: "LNG export",
      ipoVal: 55,
      currentCap: 17,
      ret: -0.6909,
      moic: 0.3091,
      bucket: "$40B+",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      qqqAtIPO: 425,
      spyAtIPO: 487,
      qqqRet: 0.6955,
      spyRet: 0.2464,
      alphaQQQ: -1.386,
      alphaSPY: -0.937,
      beatQQQ: false,
      beatSPY: false,
      wideBucket: "$40B+"
    },
    {
      year: 2020,
      ticker: "ABNB",
      company: "Airbnb",
      sector: "Consumer",
      subSector: "Travel / marketplace",
      ipoVal: 47.3,
      currentCap: 84.119,
      ret: 0.7784,
      moic: 1.7784,
      bucket: "$40B+",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$40B+"
    },
    {
      year: 2020,
      ticker: "SNOW",
      company: "Snowflake",
      sector: "SaaS / Software",
      subSector: "Data cloud platform",
      ipoVal: 33.2,
      currentCap: 52.702,
      ret: 0.5874,
      moic: 1.5874,
      bucket: "$20-40B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$20-40B"
    },
    {
      year: 2020,
      ticker: "DASH",
      company: "DoorDash",
      sector: "Marketplace / Commerce",
      subSector: "Food delivery marketplace",
      ipoVal: 32.4,
      currentCap: 71.427,
      ret: 1.2045,
      moic: 2.2045,
      bucket: "$20-40B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$20-40B"
    },
    {
      year: 2020,
      ticker: "PLTR",
      company: "Palantir Technologies",
      sector: "AI / Data Infra",
      subSector: "AI / defense analytics",
      ipoVal: 21.8,
      currentCap: 330.35,
      ret: 14.1537,
      moic: 15.1537,
      bucket: "$20-40B",
      outcome: "100%+ Winner",
      listingType: "Direct listing",
      status: "Active",
      wideBucket: "$20-40B"
    },
    {
      year: 2020,
      ticker: "GDRX",
      company: "GoodRx Holdings",
      sector: "Healthcare",
      subSector: "Healthtech / pharmacy savings",
      ipoVal: 18.9,
      currentCap: 0.989,
      ret: -0.9477,
      moic: 0.0523,
      bucket: "$10-20B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$10-20B"
    },
    {
      year: 2020,
      ticker: "WISH",
      company: "ContextLogic (Wish)",
      sector: "Marketplace / Commerce",
      subSector: "Ecommerce / discount marketplace",
      ipoVal: 14.1,
      currentCap: 0.17,
      ret: -0.9879,
      moic: 0.0121,
      bucket: "$10-20B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Acquired",
      wideBucket: "$10-20B"
    },
    {
      year: 2020,
      ticker: "U",
      company: "Unity Technologies",
      sector: "SaaS / Software",
      subSector: "Gaming engine / developer platform",
      ipoVal: 13.7,
      currentCap: 12.293,
      ret: -0.1027,
      moic: 0.8973,
      bucket: "$10-20B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$10-20B"
    },
    {
      year: 2020,
      ticker: "LI",
      company: "Li Auto",
      sector: "Mobility / Transport",
      subSector: "EV / China ADR",
      ipoVal: 10.0,
      currentCap: 18.379,
      ret: 0.8379,
      moic: 1.8379,
      bucket: "$10-20B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$10-20B"
    },
    {
      year: 2020,
      ticker: "DNB",
      company: "Dun & Bradstreet",
      sector: "SaaS / Software",
      subSector: "B2B data / analytics",
      ipoVal: 9.0,
      currentCap: 8.8,
      ret: -0.0222,
      moic: 0.9778,
      bucket: "$7-10B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Acquired",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "ZI",
      company: "ZoomInfo Technologies",
      sector: "SaaS / Software",
      subSector: "SaaS / sales intelligence",
      ipoVal: 8.2,
      currentCap: 3.6,
      ret: -0.561,
      moic: 0.439,
      bucket: "$7-10B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Acquired",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "ROOT",
      company: "Root Insurance",
      sector: "Insurance",
      subSector: "Insurtech / auto insurance",
      ipoVal: 6.7,
      currentCap: 0.893,
      ret: -0.8667,
      moic: 0.1333,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "AI",
      company: "C3.ai",
      sector: "AI / Data Infra",
      subSector: "Enterprise AI software",
      ipoVal: 6.5,
      currentCap: 1.434,
      ret: -0.7794,
      moic: 0.2206,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "ASAN",
      company: "Asana",
      sector: "SaaS / Software",
      subSector: "SaaS / work management",
      ipoVal: 5.6,
      currentCap: 1.579,
      ret: -0.718,
      moic: 0.282,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Direct listing",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "AMWL",
      company: "Amwell",
      sector: "Healthcare",
      subSector: "Healthtech / telemedicine",
      ipoVal: 5.0,
      currentCap: 0.133,
      ret: -0.9734,
      moic: 0.0266,
      bucket: "$5-7B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "FROG",
      company: "JFrog",
      sector: "SaaS / Software",
      subSector: "DevOps / software delivery",
      ipoVal: 3.9,
      currentCap: 8.548,
      ret: 1.1918,
      moic: 2.1918,
      bucket: "$3-5B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "NCNO",
      company: "nCino",
      sector: "Fintech",
      subSector: "Fintech / banking SaaS",
      ipoVal: 3.0,
      currentCap: 2.036,
      ret: -0.3213,
      moic: 0.6787,
      bucket: "$3-5B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "JAMF",
      company: "Jamf Holding",
      sector: "SaaS / Software",
      subSector: "SaaS / Apple device management",
      ipoVal: 3.0,
      currentCap: 2.8,
      ret: -0.0667,
      moic: 0.9333,
      bucket: "$3-5B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Acquired",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "SUMO",
      company: "Sumo Logic",
      sector: "Cybersecurity",
      subSector: "SaaS / security analytics",
      ipoVal: 2.7,
      currentCap: 1.69,
      ret: -0.3741,
      moic: 0.6259,
      bucket: "$2-3B",
      outcome: "Moderate Loss",
      listingType: "Traditional IPO",
      status: "Acquired",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "VRM",
      company: "Vroom",
      sector: "Marketplace / Commerce",
      subSector: "Online used car marketplace",
      ipoVal: 2.5,
      currentCap: 0.03,
      ret: -0.988,
      moic: 0.012,
      bucket: "$2-3B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Bankrupt",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "STEP",
      company: "StepStone Group",
      sector: "Asset Management",
      subSector: "Private markets asset management",
      ipoVal: 2.2,
      currentCap: 6.967,
      ret: 2.1668,
      moic: 3.1668,
      bucket: "$2-3B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "UPST",
      company: "Upstart Holdings",
      sector: "Fintech",
      subSector: "Fintech / AI lending",
      ipoVal: 1.8,
      currentCap: 2.772,
      ret: 0.54,
      moic: 1.54,
      bucket: "$1-2B",
      outcome: "Positive",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "LMND",
      company: "Lemonade",
      sector: "Insurance",
      subSector: "Insurtech / homeowners insurance",
      ipoVal: 1.6,
      currentCap: 4.226,
      ret: 1.6412,
      moic: 2.6412,
      bucket: "$1-2B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "BIGC",
      company: "BigCommerce Holdings",
      sector: "SaaS / Software",
      subSector: "SaaS / ecommerce platform",
      ipoVal: 1.5,
      currentCap: 0.22,
      ret: -0.8533,
      moic: 0.1467,
      bucket: "$1-2B",
      outcome: "50%+ Decline",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    },
    {
      year: 2020,
      ticker: "ACMR",
      company: "ACM Research",
      sector: "Semiconductors",
      subSector: "Semiconductor / wafer cleaning",
      ipoVal: 1.2,
      currentCap: 3.963,
      ret: 2.3025,
      moic: 3.3025,
      bucket: "$1-2B",
      outcome: "100%+ Winner",
      listingType: "Traditional IPO",
      status: "Active",
      wideBucket: "$0-10B"
    }
  ];

export const WIDE_BUCKETS = [
    {
      label: "$0-10B",
      n: 71,
      winRate: 0.3803,
      meanRet: 0.9581,
      medRet: -0.1408,
      bigWin: 0.2254,
      bigLoss: 0.3099,
      color: "#3fb950",
      note: "Power-law distribution: a handful of outliers (PLTR, CRDO, HOOD, DASH, ATAT) drive the mean. The median tells the real story \u2014 most companies lose value. The alpha is in picking the outliers early.",
      examples: [
        {
          t: "CRDO",
          v: 1.6,
          mc: 36.197,
          ret: 21.6231
        },
        {
          t: "GPCR",
          v: 0.8,
          mc: 8.497,
          ret: 9.6212
        },
        {
          t: "ATAT",
          v: 1.5,
          mc: 15.723,
          ret: 9.482
        },
        {
          t: "HOOD",
          v: 8,
          mc: 70.485,
          ret: 7.8106
        },
        {
          t: "ALAB",
          v: 5.5,
          mc: 36.193,
          ret: 5.5805
        },
        {
          t: "BIRD",
          v: 4.1,
          mc: 0.046,
          ret: -0.9888
        },
        {
          t: "VRM",
          v: 2.5,
          mc: 0.03,
          ret: -0.988
        },
        {
          t: "AMWL",
          v: 5.0,
          mc: 0.133,
          ret: -0.9734
        }
      ]
    },
    {
      label: "$10-20B",
      n: 9,
      winRate: 0.2222,
      meanRet: -0.2233,
      medRet: -0.4091,
      bigWin: 0.1111,
      bigLoss: 0.3333,
      color: "#f85149",
      note: "The dead zone persists across both 2020 and 2021-2025 cohorts. GDRX (-95%), WISH (-99%), U (-10%), LI (+84%) \u2014 only 3 of 9 companies are above water. Priced for perfection with no margin for error.",
      examples: [
        {
          t: "ONON",
          v: 10,
          mc: 20,
          ret: 1
        },
        {
          t: "LI",
          v: 10.0,
          mc: 18.379,
          ret: 0.8379
        },
        {
          t: "XPEV",
          v: 15,
          mc: 14,
          ret: -0.0667
        },
        {
          t: "U",
          v: 13.7,
          mc: 12.293,
          ret: -0.1027
        },
        {
          t: "DOCS",
          v: 11,
          mc: 6.5,
          ret: -0.4091
        },
        {
          t: "WISH",
          v: 14.1,
          mc: 0.17,
          ret: -0.9879
        },
        {
          t: "GDRX",
          v: 18.9,
          mc: 0.989,
          ret: -0.9477
        },
        {
          t: "TASK",
          v: 10,
          mc: 1.5,
          ret: -0.85
        }
      ]
    },
    {
      label: "$20-40B",
      n: 7,
      winRate: 0.7143,
      meanRet: 2.5057,
      medRet: 0.5874,
      bigWin: 0.4286,
      bigLoss: 0.0,
      color: "#39d2c0",
      note: "Palantir alone rewrites this bucket's story: +1415% from a $21.8B direct listing. Without PLTR, the bucket median is deeply negative. SNOW (+59%), DASH (+120%), ABNB... wait, those are in $40B+. The rule: you need a once-in-a-decade company at this valuation.",
      examples: [
        {
          t: "PLTR",
          v: 21.8,
          mc: 330.35,
          ret: 14.1537
        },
        {
          t: "CRWV",
          v: 23,
          mc: 63,
          ret: 1.7391
        },
        {
          t: "DASH",
          v: 32.4,
          mc: 71.427,
          ret: 1.2045
        },
        {
          t: "SNOW",
          v: 33.2,
          mc: 52.702,
          ret: 0.5874
        },
        {
          t: "RBLX",
          v: 38,
          mc: 38,
          ret: 0
        },
        {
          t: "TOST",
          v: 20,
          mc: 18,
          ret: -0.1
        },
        {
          t: "MDLN",
          v: 38,
          mc: 36.3,
          ret: -0.0447
        }
      ]
    },
    {
      label: "$40B+",
      n: 7,
      winRate: 0.2857,
      meanRet: -0.0213,
      medRet: -0.3,
      bigWin: 0.1429,
      bigLoss: 0.4286,
      color: "#e3a85a",
      note: "Mega-IPO graveyard \u2014 but the 2020 class added ABNB (+78%), which is a win. ARM (+196%) remains the standout in the 2021-2025 era. The median is still deeply negative: RIVN, DiDi, GDRX, Venture Global. Scale alone doesn't protect you.",
      examples: [
        {
          t: "ARM",
          v: 54,
          mc: 160,
          ret: 1.963
        },
        {
          t: "ABNB",
          v: 47.3,
          mc: 84.119,
          ret: 0.7784
        },
        {
          t: "COIN",
          v: 65,
          mc: 55,
          ret: -0.1538
        },
        {
          t: "CPNG",
          v: 60,
          mc: 42,
          ret: -0.3
        },
        {
          t: "VG",
          v: 55,
          mc: 17,
          ret: -0.6909
        },
        {
          t: "DIDI",
          v: 68,
          mc: 0.5,
          ret: -0.9926
        },
        {
          t: "RIVN",
          v: 77,
          mc: 19,
          ret: -0.7532
        }
      ]
    }
  ];

export const FINE_BUCKETS = [
    {
      label: "<$1B",
      n: 6,
      winRate: 0.3333,
      meanRet: 2.1509,
      medRet: -0.0307,
      bigWin: 0.3333,
      bigLoss: 0.1667,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "GPCR",
          v: 0.8,
          mc: 8.497,
          ret: 9.6212
        },
        {
          t: "APGE",
          v: 0.9,
          mc: 4.88,
          ret: 4.4222
        },
        {
          t: "TWG",
          v: 0.1,
          mc: 0.097,
          ret: -0.03
        },
        {
          t: "TXO",
          v: 0.7,
          mc: 0.678,
          ret: -0.0314
        },
        {
          t: "LXEO",
          v: 0.5,
          mc: 0.356,
          ret: -0.288
        },
        {
          t: "CRGX",
          v: 0.9,
          mc: 0.19,
          ret: -0.7889
        }
      ]
    },
    {
      label: "$1-2B",
      n: 10,
      winRate: 0.6,
      meanRet: 3.7917,
      medRet: 1.0906,
      bigWin: 0.5,
      bigLoss: 0.1,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "CRDO",
          v: 1.6,
          mc: 36.197,
          ret: 21.6231
        },
        {
          t: "ATAT",
          v: 1.5,
          mc: 15.723,
          ret: 9.482
        },
        {
          t: "KGS",
          v: 1.2,
          mc: 6.063,
          ret: 4.0525
        },
        {
          t: "ACMR",
          v: 1.2,
          mc: 3.963,
          ret: 2.3025
        },
        {
          t: "LMND",
          v: 1.6,
          mc: 4.226,
          ret: 1.6412
        },
        {
          t: "BIGC",
          v: 1.5,
          mc: 0.22,
          ret: -0.8533
        },
        {
          t: "NRDS",
          v: 1.2,
          mc: 0.635,
          ret: -0.4708
        },
        {
          t: "MNTN",
          v: 1.5,
          mc: 1.2,
          ret: -0.2
        }
      ]
    },
    {
      label: "$2-3B",
      n: 8,
      winRate: 0.375,
      meanRet: 0.2682,
      medRet: -0.2871,
      bigWin: 0.25,
      bigLoss: 0.375,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "CAVA",
          v: 2.5,
          mc: 9.391,
          ret: 2.7564
        },
        {
          t: "STEP",
          v: 2.2,
          mc: 6.967,
          ret: 2.1668
        },
        {
          t: "HSAI",
          v: 2.4,
          mc: 2.801,
          ret: 0.1671
        },
        {
          t: "HNGE",
          v: 2.5,
          mc: 2,
          ret: -0.2
        },
        {
          t: "SUMO",
          v: 2.7,
          mc: 1.69,
          ret: -0.3741
        },
        {
          t: "VRM",
          v: 2.5,
          mc: 0.03,
          ret: -0.988
        },
        {
          t: "ODD",
          v: 2.8,
          mc: 0.841,
          ret: -0.6996
        },
        {
          t: "IBTA",
          v: 2.7,
          mc: 0.857,
          ret: -0.6826
        }
      ]
    },
    {
      label: "$3-5B",
      n: 14,
      winRate: 0.4286,
      meanRet: 0.1577,
      medRet: -0.1595,
      bigWin: 0.1429,
      bigLoss: 0.3571,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "NXT",
          v: 3.5,
          mc: 19.38,
          ret: 4.5371
        },
        {
          t: "FROG",
          v: 3.9,
          mc: 8.548,
          ret: 1.1918
        },
        {
          t: "GLBE",
          v: 3.6,
          mc: 4.976,
          ret: 0.3822
        },
        {
          t: "DUOL",
          v: 3.7,
          mc: 5.032,
          ret: 0.36
        },
        {
          t: "VOYG",
          v: 3.8,
          mc: 5,
          ret: 0.3158
        },
        {
          t: "BIRD",
          v: 4.1,
          mc: 0.046,
          ret: -0.9888
        },
        {
          t: "GEMI",
          v: 3.3,
          mc: 0.35,
          ret: -0.8939
        },
        {
          t: "UDMY",
          v: 3.7,
          mc: 0.704,
          ret: -0.8097
        }
      ]
    },
    {
      label: "$5-7B",
      n: 16,
      winRate: 0.3125,
      meanRet: 0.5482,
      medRet: -0.4316,
      bigWin: 0.25,
      bigLoss: 0.4375,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "ALAB",
          v: 5.5,
          mc: 36.193,
          ret: 5.5805
        },
        {
          t: "CRCL",
          v: 5.4,
          mc: 28.2,
          ret: 4.2222
        },
        {
          t: "RDDT",
          v: 6.4,
          mc: 31.553,
          ret: 3.9302
        },
        {
          t: "RBRK",
          v: 5.6,
          mc: 12.367,
          ret: 1.2084
        },
        {
          t: "TEM",
          v: 6.1,
          mc: 8.923,
          ret: 0.4628
        },
        {
          t: "AMWL",
          v: 5.0,
          mc: 0.133,
          ret: -0.9734
        },
        {
          t: "ROOT",
          v: 6.7,
          mc: 0.893,
          ret: -0.8667
        },
        {
          t: "SG",
          v: 5.5,
          mc: 0.842,
          ret: -0.8469
        }
      ]
    },
    {
      label: "$7-10B",
      n: 17,
      winRate: 0.2941,
      meanRet: 0.2396,
      medRet: -0.1025,
      bigWin: 0.0588,
      bigLoss: 0.2941,
      color: "#3fb950",
      note: "",
      examples: [
        {
          t: "HOOD",
          v: 8,
          mc: 70.485,
          ret: 7.8106
        },
        {
          t: "TPG",
          v: 9.1,
          mc: 17.121,
          ret: 0.8814
        },
        {
          t: "FIG",
          v: 8.3,
          mc: 10.8,
          ret: 0.3012
        },
        {
          t: "SRVT",
          v: 7.4,
          mc: 8.5,
          ret: 0.1486
        },
        {
          t: "CART",
          v: 9.9,
          mc: 10.233,
          ret: 0.0336
        },
        {
          t: "BMBL",
          v: 8.2,
          mc: 0.472,
          ret: -0.9424
        },
        {
          t: "STUB",
          v: 8.6,
          mc: 1,
          ret: -0.8837
        },
        {
          t: "LZ",
          v: 7,
          mc: 1.085,
          ret: -0.845
        }
      ]
    },
    {
      label: "$10-20B",
      n: 9,
      winRate: 0.2222,
      meanRet: -0.2233,
      medRet: -0.4091,
      bigWin: 0.1111,
      bigLoss: 0.3333,
      color: "#f85149",
      note: "",
      examples: [
        {
          t: "ONON",
          v: 10,
          mc: 20,
          ret: 1
        },
        {
          t: "LI",
          v: 10.0,
          mc: 18.379,
          ret: 0.8379
        },
        {
          t: "XPEV",
          v: 15,
          mc: 14,
          ret: -0.0667
        },
        {
          t: "U",
          v: 13.7,
          mc: 12.293,
          ret: -0.1027
        },
        {
          t: "DOCS",
          v: 11,
          mc: 6.5,
          ret: -0.4091
        },
        {
          t: "WISH",
          v: 14.1,
          mc: 0.17,
          ret: -0.9879
        },
        {
          t: "GDRX",
          v: 18.9,
          mc: 0.989,
          ret: -0.9477
        },
        {
          t: "TASK",
          v: 10,
          mc: 1.5,
          ret: -0.85
        }
      ]
    },
    {
      label: "$20-40B",
      n: 7,
      winRate: 0.7143,
      meanRet: 2.5057,
      medRet: 0.5874,
      bigWin: 0.4286,
      bigLoss: 0.0,
      color: "#39d2c0",
      note: "",
      examples: [
        {
          t: "PLTR",
          v: 21.8,
          mc: 330.35,
          ret: 14.1537
        },
        {
          t: "CRWV",
          v: 23,
          mc: 63,
          ret: 1.7391
        },
        {
          t: "DASH",
          v: 32.4,
          mc: 71.427,
          ret: 1.2045
        },
        {
          t: "SNOW",
          v: 33.2,
          mc: 52.702,
          ret: 0.5874
        },
        {
          t: "RBLX",
          v: 38,
          mc: 38,
          ret: 0
        },
        {
          t: "TOST",
          v: 20,
          mc: 18,
          ret: -0.1
        },
        {
          t: "MDLN",
          v: 38,
          mc: 36.3,
          ret: -0.0447
        }
      ]
    },
    {
      label: "$40B+",
      n: 7,
      winRate: 0.2857,
      meanRet: -0.0213,
      medRet: -0.3,
      bigWin: 0.1429,
      bigLoss: 0.4286,
      color: "#e3a85a",
      note: "",
      examples: [
        {
          t: "ARM",
          v: 54,
          mc: 160,
          ret: 1.963
        },
        {
          t: "ABNB",
          v: 47.3,
          mc: 84.119,
          ret: 0.7784
        },
        {
          t: "COIN",
          v: 65,
          mc: 55,
          ret: -0.1538
        },
        {
          t: "CPNG",
          v: 60,
          mc: 42,
          ret: -0.3
        },
        {
          t: "VG",
          v: 55,
          mc: 17,
          ret: -0.6909
        },
        {
          t: "DIDI",
          v: 68,
          mc: 0.5,
          ret: -0.9926
        },
        {
          t: "RIVN",
          v: 77,
          mc: 19,
          ret: -0.7532
        }
      ]
    }
  ];

export const YEAR_STATS = [
    {
      year: 2020,
      n: 24,
      winRate: 0.4167,
      meanRet: 0.7017,
      medRet: -0.0847,
      bigWin: 0.25,
      bigLoss: 0.375
    },
    {
      year: 2021,
      n: 27,
      winRate: 0.1852,
      meanRet: -0.1067,
      medRet: -0.4708,
      bigWin: 0.0741,
      bigLoss: 0.4074
    },
    {
      year: 2022,
      n: 5,
      winRate: 0.6,
      meanRet: 6.3735,
      medRet: 0.8814,
      bigWin: 0.4,
      bigLoss: 0.0
    },
    {
      year: 2023,
      n: 13,
      winRate: 0.6154,
      meanRet: 1.9339,
      medRet: 0.1671,
      bigWin: 0.4615,
      bigLoss: 0.1538
    },
    {
      year: 2024,
      n: 10,
      winRate: 0.6,
      meanRet: 1.0041,
      medRet: 0.1381,
      bigWin: 0.3,
      bigLoss: 0.2
    },
    {
      year: 2025,
      n: 15,
      winRate: 0.2667,
      meanRet: 0.1596,
      medRet: -0.2,
      bigWin: 0.1333,
      bigLoss: 0.2667
    }
  ];

export const SECTOR_STATS = [
    {
      sector: "AI / Data Infra",
      n: 3,
      winRate: 0.6667,
      meanRet: 5.0378,
      medRet: 1.7391,
      bigWin: 0.6667,
      bigLoss: 0.3333
    },
    {
      sector: "Adtech",
      n: 1,
      winRate: 0.0,
      meanRet: -0.2,
      medRet: -0.2,
      bigWin: 0.0,
      bigLoss: 0.0
    },
    {
      sector: "Asset Management",
      n: 2,
      winRate: 1.0,
      meanRet: 1.5241,
      medRet: 1.5241,
      bigWin: 0.5,
      bigLoss: 0.0
    },
    {
      sector: "Consumer",
      n: 15,
      winRate: 0.4,
      meanRet: 0.2419,
      medRet: -0.1408,
      bigWin: 0.2,
      bigLoss: 0.3333
    },
    {
      sector: "Crypto / Web3",
      n: 3,
      winRate: 0.3333,
      meanRet: 1.0582,
      medRet: -0.1538,
      bigWin: 0.3333,
      bigLoss: 0.3333
    },
    {
      sector: "Cybersecurity",
      n: 2,
      winRate: 0.5,
      meanRet: 0.4171,
      medRet: 0.4171,
      bigWin: 0.5,
      bigLoss: 0.0
    },
    {
      sector: "Edtech",
      n: 1,
      winRate: 0.0,
      meanRet: -0.7733,
      medRet: -0.7733,
      bigWin: 0.0,
      bigLoss: 1.0
    },
    {
      sector: "Energy / Industrials",
      n: 5,
      winRate: 0.4,
      meanRet: 1.5707,
      medRet: -0.014,
      bigWin: 0.4,
      bigLoss: 0.2
    },
    {
      sector: "Fintech",
      n: 10,
      winRate: 0.3,
      meanRet: 0.5735,
      medRet: -0.2616,
      bigWin: 0.1,
      bigLoss: 0.2
    },
    {
      sector: "Healthcare",
      n: 11,
      winRate: 0.2727,
      meanRet: 0.9788,
      medRet: -0.2,
      bigWin: 0.1818,
      bigLoss: 0.2727
    },
    {
      sector: "Hospitality",
      n: 1,
      winRate: 1.0,
      meanRet: 9.482,
      medRet: 9.482,
      bigWin: 1.0,
      bigLoss: 0.0
    },
    {
      sector: "Insurance",
      n: 4,
      winRate: 0.25,
      meanRet: 0.0728,
      medRet: -0.2417,
      bigWin: 0.25,
      bigLoss: 0.25
    },
    {
      sector: "Legaltech",
      n: 1,
      winRate: 0.0,
      meanRet: -0.845,
      medRet: -0.845,
      bigWin: 0.0,
      bigLoss: 1.0
    },
    {
      sector: "Marketplace / Commerce",
      n: 8,
      winRate: 0.375,
      meanRet: -0.2936,
      medRet: -0.5548,
      bigWin: 0.125,
      bigLoss: 0.5
    },
    {
      sector: "Mobility / Transport",
      n: 6,
      winRate: 0.3333,
      meanRet: -0.2346,
      medRet: -0.3333,
      bigWin: 0.0,
      bigLoss: 0.5
    },
    {
      sector: "Real Estate / Proptech",
      n: 1,
      winRate: 0.0,
      meanRet: -0.1025,
      medRet: -0.1025,
      bigWin: 0.0,
      bigLoss: 0.0
    },
    {
      sector: "SaaS / Software",
      n: 15,
      winRate: 0.2667,
      meanRet: -0.1754,
      medRet: -0.1027,
      bigWin: 0.0667,
      bigLoss: 0.3333
    },
    {
      sector: "Semiconductors",
      n: 4,
      winRate: 1.0,
      meanRet: 7.8673,
      medRet: 3.9415,
      bigWin: 1.0,
      bigLoss: 0.0
    },
    {
      sector: "Space / Defense",
      n: 1,
      winRate: 1.0,
      meanRet: 0.3158,
      medRet: 0.3158,
      bigWin: 0.0,
      bigLoss: 0.0
    }
  ];

export const BUCKET_BENCHMARK = [
  { bucket: "<$1B",    n: 6,  meanIPORet: 2.151,  meanQQQRet: 1.027, meanSPYRet: 0.367, meanAlphaQQQ: 1.124,  meanAlphaSPY: 1.784,  beatQQQPct: 0.333, beatSPYPct: 0.333 },
  { bucket: "$1-2B",   n: 6,  meanIPORet: 5.714,  meanQQQRet: 0.845, meanSPYRet: 0.278, meanAlphaQQQ: 4.869,  meanAlphaSPY: 5.437,  beatQQQPct: 0.500, beatSPYPct: 0.500 },
  { bucket: "$2-3B",   n: 5,  meanIPORet: 0.268,  meanQQQRet: 0.871, meanSPYRet: 0.293, meanAlphaQQQ: -0.602, meanAlphaSPY: -0.025, beatQQQPct: 0.200, beatSPYPct: 0.200 },
  { bucket: "$3-5B",   n: 11, meanIPORet: 0.128,  meanQQQRet: 0.813, meanSPYRet: 0.267, meanAlphaQQQ: -0.685, meanAlphaSPY: -0.139, beatQQQPct: 0.091, beatSPYPct: 0.182 },
  { bucket: "$5-7B",   n: 13, meanIPORet: 0.866,  meanQQQRet: 0.818, meanSPYRet: 0.279, meanAlphaQQQ: 0.049,  meanAlphaSPY: 0.587,  beatQQQPct: 0.308, beatSPYPct: 0.385 },
  { bucket: "$7-10B",  n: 14, meanIPORet: 0.393,  meanQQQRet: 0.758, meanSPYRet: 0.263, meanAlphaQQQ: -0.365, meanAlphaSPY: 0.130,  beatQQQPct: 0.143, beatSPYPct: 0.286 },
  { bucket: "$10-20B", n: 6,  meanIPORet: -0.152, meanQQQRet: 0.987, meanSPYRet: 0.391, meanAlphaQQQ: -1.138, meanAlphaSPY: -0.543, beatQQQPct: 0.167, beatSPYPct: 0.167 },
  { bucket: "$20-40B", n: 3,  meanIPORet: 0.565,  meanQQQRet: 0.725, meanSPYRet: 0.219, meanAlphaQQQ: -0.160, meanAlphaSPY: 0.346,  beatQQQPct: 0.333, beatSPYPct: 0.333 },
  { bucket: "$40B+",   n: 6,  meanIPORet: -0.155, meanQQQRet: 0.969, meanSPYRet: 0.387, meanAlphaQQQ: -1.124, meanAlphaSPY: -0.541, beatQQQPct: 0.167, beatSPYPct: 0.167 },
];
